Update lite-updatenotify

diff --git a/usr/bin/lite-updatenotify b/usr/bin/lite-updatenotify
--- a/usr/bin/lite-updatenotify
+++ b/usr/bin/lite-updatenotify
@@ -56,9 +56,9 @@ if [[ $CHFREQ =~ Disable ]]; then
         rm -rf $DIR/$USERLOGGEDIN
             if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                 zenity --question --width=380 --height=60 --icon-name=error --title="$LUN - Error" \
-                        --text="\n<b>An error occurred while scheduling updates notification</b> \n\nYou may not have sufficient permissions to perform this task. \n\nDo you want to Authenticate now and go back to $LUN to try again?"
-                        elevate=$?
-                        if [ "$elevate" -eq "0" ]; then
+                       --text="\n<b>An error occurred while scheduling updates notification</b> \n\nYou may not have sufficient permissions to perform this task. \n\nDo you want to Authenticate now and go back to $LUN to try again?"
+                       elevate=$?
+                       if [ "$elevate" -eq "0" ]; then
                             gksu bash $0
                             exit
                         else
@@ -93,15 +93,15 @@ elif [[ $CHFREQ =~ "Every 3 Weeks" ]]; then
 fi
 
 if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-        zenity --question --width=340 --height=60 --title="$LUN - Error" \
-                        --text="\nAn error occurred while scheduling updates notification. \nYou may not have sufficient permissions to perform this task. You may want to Authenticate now?"
-                        elevate=$?
-                        if [ "$elevate" -eq "0" ]; then
-                            gksu bash $0
-                            exit
-                        else
-                            exit 0
-                        fi
+        zenity --question --width=380 --height=60 --icon-name=error --title="$LUN - Error" \
+               --text="\n<b>An error occurred while scheduling updates notification</b> \n\nYou may not have sufficient permissions to perform this task. \n\nDo you want to Authenticate now and go back to $LUN to try again?"
+                elevate=$?
+                if [ "$elevate" -eq "0" ]; then
+                    gksu bash $0
+                    exit
+                else
+                exit 0
+            fi
         continue
     else
         zenity --width=320 --height=60 --info --timeout=3 --title=" $LUN" --text="\nUpdates notification has been successfully scheduled."
