Update lite-updatenotify

diff --git a/usr/bin/lite-updatenotify b/usr/bin/lite-updatenotify
--- a/usr/bin/lite-updatenotify
+++ b/usr/bin/lite-updatenotify
@@ -9,77 +9,103 @@
 # Ensure multi-language support
 export LANG=C
 
-# Set the window icon variable
+# set the window icon variable
 ic="/usr/share/icons/zenity-llcc.png"
 
-# Set user logged in as variable
-USERLOGGEDIN=$(whoami)
+USERLOGGEDIN=$(sudo -u ${SUDO_USER:-$USER} whoami)  # set sudoer user as variable
+DIR=/var/spool/cron/crontabs/                       # set working dir variable
+LUN="Lite Updates Notify"                           # Lite Updates Notify Titlebar
+UNI="Update Notification Interval"                  # UNI Zenity message
+APPICON=/usr/local/sbin/icons/          # Set app icon variable
 
-# Set working dir variable
-DIR=/var/spool/cron/crontabs/
-
-# Check if User is member of 'sudo' group
-if [ "$(whoami)" != "root" ]; then
-    (zenity --info --ok-label="Got it!" --title="You are not an Administrator" \
-            --text="\n<b>You need to be an Administrator to use this application</b> \n \nAsk your System Administrator to add you to the <b>sudo</b> group." --no-wrap)
-	exit 1
-
+# Check administrative privileges
+if [ $EUID -ne 0 ]; then
+    zenity --question --cancel-label="Continue" --ok-label="Authenticate" --window-icon="$ic" --title=" $LUN - Are you Administrator?" \
+           --width=400 --height=50 --icon-name=info \
+           --text="\nYou need administrative privileges to make changes in $LUN.\n \nClick <b>Continue</b> to continue without administrative privileges \nor <b>Authenticate</b> to enter your password next." --no-wrap
+   case $? in
+    0) gksu bash $0
+       exit;;
+    1) continue
+    esac
 fi
 
-# Lite Updates Notify Titlebar
-LUN="Lite Updates Notify"
-
-# UNI Zenity message
-UNI="Update Notification Interval"
-
-# Set app icon variable
-APPICON=/usr/share/liteupdatenotify/icons/
-
 # Start main dialogue
+while (true); do
+CHFREQ=$(zenity --list --width="480" --height=320 --title="     $LUN" --ok-label="Set" --cancel-label="Quit" --window-icon=$ic \
+--text "Set the Updates notification frequency from the options below:\n" \
+--column "     Frequency   " --column "Description" \
+" ✔ Hourly" " Once every hour eg. 1pm, 2pm, 3pm etc" \
+" ✔ Every 6 Hours" " First run at midnight, then every 6 hours" \
+" ✔ Every 12 Hours" " First run at midnight, then every 12 hours" \
+" ✔ Daily" " Every day at 7pm" \
+" ✔ Every other Day     " " Every other day at 7pm" \
+" ✔ Weekly" " Once every week at 7pm on a Monday" \
+" ✔ Every 2 Weeks" " Once every 2 weeks at 7pm on a Monday" \
+" ✔ Every 3 Weeks" " Once every 3 weeks at 7pm on a Monday" \
+" ✘ Disable" "Disable Updates Notification")
 
-CHFREQ=$(zenity --title="$LUN" \
---ok-label="Set Frequency" \
---height=360 --width="560" \
---window-icon=$ic \
---list --imagelist --text "Select an Update notification frequency from below:\n" \
---column "  Select  " --column " Frequency" --column " Description" \
-"$APPICON/clock.png" " Hourly" " Once every hour eg. 1pm, 2pm, 3pm etc" \
-"$APPICON/clock.png" " Every 6 Hours" " First run at midnight, then every 6 hours" \
-"$APPICON/clock.png" " Every 12 Hours" " First run at midnight, then every 12 hours" \
-"$APPICON/clock.png" " Daily" " Every day at 7pm" \
-"$APPICON/clock.png" " Every other Day" " Every other day at 7pm" \
-"$APPICON/clock.png" " Weekly" " Once every week at 7pm on a Monday" \
-"$APPICON/clock.png" " Every 2 Weeks" " Once every 2 weeks at 7pm on a Monday" \
-"$APPICON/clock.png" " Every 3 Weeks" " Once every 3 weeks at 7pm on a Monday")
+if [ "$?" -eq "1" ]; then
+    exit 0
+fi 
 
-if [[ "$CHFREQ" =~ " Hourly" ]]; then
-    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && echo "0 * * * * su $USERLOGGEDIN -c /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN | zenity --progress --title="$LUN" --text="Setting $UNI, please do not interrupt this operation..." --pulsate --auto-kill --auto-close
-
-elif [[ "$CHFREQ" =~ " Every 6 Hours" ]]; then
-    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && echo "0 */6 * * * su $USERLOGGEDIN -c /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN | zenity --progress --title="$LUN" --text="Setting $UNI, please do not interrupt this operation..." --pulsate --auto-kill --auto-close
-
-elif [[ "$CHFREQ" =~ " Every 12 Hours" ]]; then
-    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && echo "0 */12 * * * su $USERLOGGEDIN -c /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN | zenity --progress --title="$LUN" --text="Setting $UNI, please do not interrupt this operation..." --pulsate --auto-kill --auto-close
-
-elif [[ "$CHFREQ" =~ " Daily" ]]; then
-    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && echo "0 19 * * * su $USERLOGGEDIN -c /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN | zenity --progress --title="$LUN" --text="Setting $UNI, please do not interrupt this operation..." --pulsate --auto-kill --auto-close
-
-elif [[ "$CHFREQ" =~ " Every other Day" ]]; then
-    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && echo "0 19 */2 * * su $USERLOGGEDIN -c /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN | zenity --progress --title="$LUN" --text="Setting $UNI, please do not interrupt this operation..." --pulsate --auto-kill --auto-close
-
-elif [[ "$CHFREQ" =~ " Weekly" ]]; then
-    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && echo "0 19 */7 * 1 su $USERLOGGEDIN -c /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN | zenity --progress --title="$LUN" --text="Setting $UNI, please do not interrupt this operation..." --pulsate --auto-kill --auto-close
-
-elif [[ "$CHFREQ" =~ " Every 2 Weeks" ]]; then
-    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && echo "0 19 */14 * 1 su $USERLOGGEDIN -c /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN | zenity --progress --title="$LUN" --text="Setting $UNI, please do not interrupt this operation..." --pulsate --auto-kill --auto-close
-
-elif [[ "$CHFREQ" =~ " Every 3 Weeks" ]]; then
-    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && echo "0 19 */21 * 1 su $USERLOGGEDIN -c /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN | zenity --progress --title="$LUN" --text="Setting $UNI, please do not interrupt this operation..." --pulsate --auto-kill --auto-close
-
-            else
-
-                                        zenity --error \
-                                        --title="$LUN" --width=140 --text="An error occured! \n\nPlease try again."
+if [[ $CHFREQ =~ Disable ]]; then
+    zenity --question --title=" $LUN" --text="\nAre you sure you want to disable Lite Updates notifications?"
+    confirm=$?
+    if [ "$confirm" -eq "0" ]; then
+        rm -rf $DIR/$USERLOGGEDIN
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                zenity --question --width=380 --height=60 --icon-name=error --title="$LUN - Error" \
+                        --text="\n<b>An error occurred while scheduling updates notification</b> \n\nYou may not have sufficient permissions to perform this task. \n\nDo you want to Authenticate now and go back to $LUN to try again?"
+                        elevate=$?
+                        if [ "$elevate" -eq "0" ]; then
+                            gksu bash $0
+                            exit
+                        else
+                            exit 0
                         fi
+                continue
+            else
+                zenity --info --timeout=3 --title=" $LUN" --text="\nNotification Updates have been disabled!"
+                exit 0
+            fi
+        else
+            continue
+    fi 
+fi
+# set cron schedule
+if [[ $CHFREQ =~ Hourly ]]; then
+    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && chmod +x $DIR/$USERLOGGEDIN && printf "#!/bin/sh \n0 * * * * $USERLOGGEDIN ionice -c2 -p\$\$ -n 7;nice -n 19 /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN
+elif [[ $CHFREQ =~ "Every 6 Hours" ]]; then
+    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && chmod +x $DIR/$USERLOGGEDIN && printf "#!/bin/sh \n0 */6 * * * $USERLOGGEDIN ionice -c2 -p\$\$ -n 7;nice -n 19 /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN
+elif [[ $CHFREQ =~ "Every 12 Hours" ]]; then
+    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && chmod +x $DIR/$USERLOGGEDIN && printf "#!/bin/sh \n0 */12 * * * $USERLOGGEDIN ionice -c2 -p\$\$ -n 7;nice -n 19 /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN
+elif [[ $CHFREQ =~ Daily ]]; then
+    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && chmod +x $DIR/$USERLOGGEDIN && printf "#!/bin/sh \n0 19 * * * $USERLOGGEDIN ionice -c2 -p\$\$ -n 7;nice -n 19 /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN
+elif [[ $CHFREQ =~ "Every other Day" ]]; then
+    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && chmod +x $DIR/$USERLOGGEDIN && printf "#!/bin/sh \n0 19 */2 * * $USERLOGGEDIN ionice -c2 -p\$\$ -n 7;nice -n 19 /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN
+elif [[ $CHFREQ =~ Weekly ]]; then
+    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && chmod +x $DIR/$USERLOGGEDIN && printf "#!/bin/sh \n0 19 */7 * 1 $USERLOGGEDIN ionice -c2 -p\$\$ -n 7;nice -n 19 /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN
+elif [[ $CHFREQ =~ "Every 2 Weeks" ]]; then
+    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && chmod +x $DIR/$USERLOGGEDIN && printf "#!/bin/sh \n0 19 */14 * 1 $USERLOGGEDIN ionice -c2 -p\$\$ -n 7;nice -n 19 /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN
+elif [[ $CHFREQ =~ "Every 3 Weeks" ]]; then
+    rm -rf $DIR/$USERLOGGEDIN && touch $DIR/$USERLOGGEDIN && chmod +x $DIR/$USERLOGGEDIN && printf "#!/bin/sh \n0 19 */21 * 1 $USERLOGGEDIN ionice -c2 -p\$\$ -n 7;nice -n 19 /usr/local/sbin/updatenotify >/dev/null 2>&1" >> $DIR/$USERLOGGEDIN
+fi
 
+if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+        zenity --question --width=340 --height=60 --title="$LUN - Error" \
+                        --text="\nAn error occurred while scheduling updates notification. \nYou may not have sufficient permissions to perform this task. You may want to Authenticate now?"
+                        elevate=$?
+                        if [ "$elevate" -eq "0" ]; then
+                            gksu bash $0
+                            exit
+                        else
+                            exit 0
+                        fi
+        continue
+    else
+        zenity --width=320 --height=60 --info --timeout=3 --title=" $LUN" --text="\nUpdates notification has been successfully scheduled."
+
+fi
+done
 exit 0
